// Starter templates — real, runnable workflows. Each is self-contained (a prompt
// node injects sample input) so it runs the moment you open it. Selecting one
// instantiates a fresh workflow the user can edit.
export interface Template {
  slug: string;
  name: string;
  description: string;
  glyph: string;
  accent: string;
  nodes: { id: string; type: string; position: { x: number; y: number }; data: Record<string, any> }[];
  edges: { id: string; source: string; target: string; sourceHandle?: string | null }[];
}

const SAMPLE_EMAIL =
  "Subject: Double charged this month\n\nHi — I just noticed my card was billed twice for my Pro subscription this month. Can you refund the extra charge? Thanks, Dana";

const SAMPLE_GUEST =
  "Hi! I'd love to book a table for 4 this Friday around 7pm under the name Alex. Do you have anything by the window?";

const SAMPLE_CLAUSE =
  "The Provider shall indemnify and hold harmless the Client against any and all claims arising from data breaches, with liability capped at fees paid in the preceding 12 months. This clause survives termination.";

export const TEMPLATES: Template[] = [
  {
    slug: "support-triage",
    name: "Support Email Triage",
    description: "Classify an incoming email as billing / bug / sales and draft a tailored reply.",
    glyph: "✉",
    accent: "#4fd1c5",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "email", type: "prompt", position: { x: 300, y: 200 }, data: { template: SAMPLE_EMAIL } },
      { id: "classify", type: "llm", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", system: "Reply with exactly one lowercase word — billing, bug, or sales — classifying this support email.", prompt: "{{nodes.email.output}}", temperature: 0, max_tokens: 5 } },
      { id: "route", type: "switch", position: { x: 820, y: 200 }, data: { mode: "contains", cases: "billing\nbug\nsales" } },
      { id: "billing", type: "llm", position: { x: 1090, y: 60 }, data: { model: "auto", system: "You are a billing specialist. Write a warm, specific reply that resolves the customer's billing issue.", prompt: "{{nodes.email.output}}", max_tokens: 400 } },
      { id: "bug", type: "llm", position: { x: 1090, y: 210 }, data: { model: "auto", system: "You are a support engineer. Acknowledge the bug and give clear next steps.", prompt: "{{nodes.email.output}}", max_tokens: 400 } },
      { id: "sales", type: "llm", position: { x: 1090, y: 360 }, data: { model: "auto", system: "You are a sales rep. Reply enthusiastically and propose a quick demo.", prompt: "{{nodes.email.output}}", max_tokens: 400 } },
      { id: "end", type: "end", position: { x: 1360, y: 210 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "email" },
      { id: "e2", source: "email", target: "classify" },
      { id: "e3", source: "classify", target: "route" },
      { id: "e4", source: "route", target: "billing", sourceHandle: "billing" },
      { id: "e5", source: "route", target: "bug", sourceHandle: "bug" },
      { id: "e6", source: "route", target: "sales", sourceHandle: "sales" },
      { id: "e7", source: "billing", target: "end" },
      { id: "e8", source: "bug", target: "end" },
      { id: "e9", source: "sales", target: "end" },
    ],
  },
  {
    slug: "restaurant-concierge",
    name: "Restaurant Concierge",
    description: "Read a guest message, extract the booking details, and compose a confirmation email.",
    glyph: "◷",
    accent: "#7c5cfc",
    nodes: [
      { id: "hook", type: "webhook", position: { x: 60, y: 160 }, data: { path: "/hook/reservations" } },
      { id: "msg", type: "prompt", position: { x: 320, y: 160 }, data: { template: SAMPLE_GUEST } },
      { id: "concierge", type: "llm", position: { x: 580, y: 160 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a warm restaurant concierge. Extract the date, time, and party size from the guest message, then write a friendly confirmation.", prompt: "{{nodes.msg.output}}", max_tokens: 400 } },
      { id: "confirm", type: "email", position: { x: 840, y: 160 }, data: { to: "guest@example.com", subject: "Your reservation at Zoid Bistro", body: "{{nodes.concierge.output}}" } },
      { id: "end", type: "end", position: { x: 1100, y: 160 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "hook", target: "msg" },
      { id: "e2", source: "msg", target: "concierge" },
      { id: "e3", source: "concierge", target: "confirm" },
      { id: "e4", source: "confirm", target: "end" },
    ],
  },
  {
    slug: "doc-review",
    name: "Document Review",
    description: "Summarize a document, decide if it needs legal review, then flag or approve it.",
    glyph: "❡",
    accent: "#818cf8",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "doc", type: "prompt", position: { x: 300, y: 200 }, data: { template: SAMPLE_CLAUSE } },
      { id: "summary", type: "summarizer", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-sonnet-5", length: "short" } },
      { id: "assess", type: "llm", position: { x: 820, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", system: "Decide if this document needs legal review. Reply YES or NO, then a one-line reason.", prompt: "{{nodes.doc.output}}", temperature: 0, max_tokens: 60 } },
      { id: "gate", type: "decision", position: { x: 1080, y: 200 }, data: { mode: "contains", value: "YES" } },
      { id: "flag", type: "llm", position: { x: 1330, y: 90 }, data: { model: "anthropic/claude-sonnet-5", system: "Draft a short note flagging this document for legal review, citing the concern.", prompt: "Summary: {{nodes.summary.output}}\n\nAssessment: {{nodes.assess.output}}", max_tokens: 250 } },
      { id: "approve", type: "llm", position: { x: 1330, y: 320 }, data: { model: "anthropic/claude-sonnet-5", system: "Draft a brief note stating the document is approved with no legal concerns.", prompt: "Summary: {{nodes.summary.output}}", max_tokens: 200 } },
      { id: "end", type: "end", position: { x: 1600, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "doc" },
      { id: "e2", source: "doc", target: "summary" },
      { id: "e3", source: "summary", target: "assess" },
      { id: "e4", source: "assess", target: "gate" },
      { id: "e5", source: "gate", target: "flag", sourceHandle: "true" },
      { id: "e6", source: "gate", target: "approve", sourceHandle: "false" },
      { id: "e7", source: "flag", target: "end" },
      { id: "e8", source: "approve", target: "end" },
    ],
  },
  {
    slug: "meeting-brief",
    name: "Meeting Brief",
    description: "Turn a topic into researched talking points, then a crisp 5-bullet brief.",
    glyph: "✦",
    accent: "#22d3ee",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 160 }, data: {} },
      { id: "topic", type: "prompt", position: { x: 300, y: 160 }, data: { template: "Q3 product roadmap planning meeting" } },
      { id: "research", type: "llm", position: { x: 560, y: 160 }, data: { model: "anthropic/claude-sonnet-5", system: "List 6 concise, concrete talking points for a meeting on the given topic.", prompt: "{{nodes.topic.output}}", max_tokens: 400 } },
      { id: "brief", type: "llm", position: { x: 820, y: 160 }, data: { model: "anthropic/claude-sonnet-5", system: "Turn these talking points into a crisp meeting brief: a title line, then exactly 5 bullets.", prompt: "{{nodes.research.output}}", max_tokens: 400 } },
      { id: "end", type: "end", position: { x: 1080, y: 160 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "topic" },
      { id: "e2", source: "topic", target: "research" },
      { id: "e3", source: "research", target: "brief" },
      { id: "e4", source: "brief", target: "end" },
    ],
  },
  {
    slug: "help-desk",
    name: "Help Desk",
    description: "Triage an IT ticket by severity — page on-call for urgent, auto-reply for the rest.",
    glyph: "⚑",
    accent: "#f4b860",
    nodes: [
      { id: "hook", type: "webhook", position: { x: 60, y: 200 }, data: { path: "/hook/tickets" } },
      { id: "ticket", type: "prompt", position: { x: 320, y: 200 }, data: { template: "Ticket #4812 from dana@acme.com\n\nOur whole sales team lost VPN access an hour ago. Nobody can reach the CRM. This is blocking all customer calls." } },
      { id: "triage", type: "llm", position: { x: 580, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", system: "You are IT help-desk triage. Classify the ticket severity. Reply with exactly URGENT or ROUTINE, then a one-line reason.", prompt: "{{nodes.ticket.output}}", temperature: 0, max_tokens: 60 } },
      { id: "gate", type: "decision", position: { x: 840, y: 200 }, data: { mode: "contains", value: "URGENT" } },
      { id: "page", type: "email", position: { x: 1100, y: 90 }, data: { to: "oncall@example.com", subject: "URGENT ticket needs eyes", body: "Triage: {{nodes.triage.output}}\n\nTicket:\n{{nodes.ticket.output}}" } },
      { id: "reply", type: "llm", position: { x: 1100, y: 310 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a friendly help-desk agent. Write a short reply acknowledging the ticket, with one likely self-service step and an ETA for follow-up.", prompt: "{{nodes.ticket.output}}", max_tokens: 250 } },
      { id: "end", type: "end", position: { x: 1370, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "hook", target: "ticket" },
      { id: "e2", source: "ticket", target: "triage" },
      { id: "e3", source: "triage", target: "gate" },
      { id: "e4", source: "gate", target: "page", sourceHandle: "true" },
      { id: "e5", source: "gate", target: "reply", sourceHandle: "false" },
      { id: "e6", source: "page", target: "end" },
      { id: "e7", source: "reply", target: "end" },
    ],
  },
  {
    slug: "sales-agent",
    name: "Sales Agent",
    description: "Qualify an inbound lead, then draft a tailored pitch or a polite pass.",
    glyph: "✦",
    accent: "#7c5cfc",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "lead", type: "prompt", position: { x: 300, y: 200 }, data: { template: "Inbound from jordan@brightco.io:\n\nWe're a 120-person agency looking to automate client reporting. Budget is around $2k/month if the fit is right. Can we see a demo this month?" } },
      { id: "qualify", type: "llm", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", system: "You are a sales qualifier. Decide if this lead is qualified (clear need + budget + timeline). Reply QUALIFIED or PASS, then one line why.", prompt: "{{nodes.lead.output}}", temperature: 0, max_tokens: 60 } },
      { id: "gate", type: "decision", position: { x: 820, y: 200 }, data: { mode: "contains", value: "QUALIFIED" } },
      { id: "pitch", type: "llm", position: { x: 1080, y: 90 }, data: { model: "anthropic/claude-sonnet-5", system: "You are an enthusiastic but concise AE. Write a reply proposing two demo slots, referencing their specific need and budget fit.", prompt: "{{nodes.lead.output}}", max_tokens: 350 } },
      { id: "pass", type: "llm", position: { x: 1080, y: 310 }, data: { model: "anthropic/claude-sonnet-5", system: "Write a warm, brief reply declining for now but pointing them to self-serve resources and inviting them back as they grow.", prompt: "{{nodes.lead.output}}", max_tokens: 250 } },
      { id: "send", type: "email", position: { x: 1340, y: 200 }, data: { to: "jordan@brightco.io", subject: "Re: your demo request", body: "{{previous.output}}" } },
      { id: "end", type: "end", position: { x: 1600, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "lead" },
      { id: "e2", source: "lead", target: "qualify" },
      { id: "e3", source: "qualify", target: "gate" },
      { id: "e4", source: "gate", target: "pitch", sourceHandle: "true" },
      { id: "e5", source: "gate", target: "pass", sourceHandle: "false" },
      { id: "e6", source: "pitch", target: "send" },
      { id: "e7", source: "pass", target: "send" },
      { id: "e8", source: "send", target: "end" },
    ],
  },
  {
    slug: "email-classifier",
    name: "Email Classifier",
    description: "Sort incoming mail into work / personal / newsletter / spam with a Switch.",
    glyph: "✉",
    accent: "#22d3ee",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 240 }, data: {} },
      { id: "email", type: "prompt", position: { x: 300, y: 240 }, data: { template: "From: no-reply@dealblaster.biz\nSubject: You WON a $500 gift card!!! Claim NOW\n\nClick here immediately to claim your prize before it expires!!!" } },
      { id: "classify", type: "llm", position: { x: 560, y: 240 }, data: { model: "anthropic/claude-haiku-4.5", system: "Classify this email. Reply with exactly one lowercase word: work, personal, newsletter, or spam.", prompt: "{{nodes.email.output}}", temperature: 0, max_tokens: 5 } },
      { id: "route", type: "switch", position: { x: 820, y: 240 }, data: { mode: "contains", cases: "work\npersonal\nnewsletter\nspam" } },
      { id: "work", type: "prompt", position: { x: 1090, y: 60 }, data: { template: "📥 Filed to WORK — needs a reply today.\n\n{{nodes.email.output}}" } },
      { id: "personal", type: "prompt", position: { x: 1090, y: 190 }, data: { template: "🏠 Filed to PERSONAL.\n\n{{nodes.email.output}}" } },
      { id: "news", type: "prompt", position: { x: 1090, y: 320 }, data: { template: "📰 Filed to NEWSLETTERS — read later.\n\n{{nodes.email.output}}" } },
      { id: "spam", type: "prompt", position: { x: 1090, y: 450 }, data: { template: "🗑 Sent to SPAM. Reason: {{nodes.classify.output}}" } },
      { id: "end", type: "end", position: { x: 1360, y: 240 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "email" },
      { id: "e2", source: "email", target: "classify" },
      { id: "e3", source: "classify", target: "route" },
      { id: "e4", source: "route", target: "work", sourceHandle: "work" },
      { id: "e5", source: "route", target: "personal", sourceHandle: "personal" },
      { id: "e6", source: "route", target: "news", sourceHandle: "newsletter" },
      { id: "e7", source: "route", target: "spam", sourceHandle: "spam" },
      { id: "e8", source: "work", target: "end" },
      { id: "e9", source: "personal", target: "end" },
      { id: "e10", source: "news", target: "end" },
      { id: "e11", source: "spam", target: "end" },
    ],
  },
  {
    slug: "resume-reviewer",
    name: "Resume Reviewer",
    description: "Summarize a resume, score it against the role, and draft the right response.",
    glyph: "❡",
    accent: "#818cf8",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "resume", type: "prompt", position: { x: 300, y: 200 }, data: { template: "Role: Senior Backend Engineer (Python, Postgres, AWS)\n\nResume — Sam Rivera\n6 years Python (FastAPI, Django), 4 years Postgres incl. query tuning, led migration of a monolith to ECS on AWS. Mentored 3 juniors. Side project: open-source task queue with 2k stars." } },
      { id: "summary", type: "summarizer", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", length: "short" } },
      { id: "score", type: "llm", position: { x: 820, y: 200 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a technical recruiter. Score the candidate against the stated role: reply STRONG, MAYBE, or NO, then 2 lines of justification.", prompt: "{{nodes.resume.output}}", temperature: 0, max_tokens: 120 } },
      { id: "gate", type: "decision", position: { x: 1080, y: 200 }, data: { mode: "contains", value: "STRONG" } },
      { id: "invite", type: "llm", position: { x: 1340, y: 90 }, data: { model: "anthropic/claude-sonnet-5", system: "Draft a warm interview invitation referencing one specific strength from the resume. Offer two time slots.", prompt: "{{nodes.resume.output}}", max_tokens: 250 } },
      { id: "decline", type: "llm", position: { x: 1340, y: 310 }, data: { model: "anthropic/claude-sonnet-5", system: "Draft a kind, specific rejection that encourages a future application.", prompt: "Assessment: {{nodes.score.output}}", max_tokens: 200 } },
      { id: "end", type: "end", position: { x: 1610, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "resume" },
      { id: "e2", source: "resume", target: "summary" },
      { id: "e3", source: "summary", target: "score" },
      { id: "e4", source: "score", target: "gate" },
      { id: "e5", source: "gate", target: "invite", sourceHandle: "true" },
      { id: "e6", source: "gate", target: "decline", sourceHandle: "false" },
      { id: "e7", source: "invite", target: "end" },
      { id: "e8", source: "decline", target: "end" },
    ],
  },
  {
    slug: "legal-intake",
    name: "Legal Intake",
    description: "Read a client inquiry, route it by matter type, and prep the right intake notes.",
    glyph: "◈",
    accent: "#f4b860",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "inquiry", type: "prompt", position: { x: 300, y: 200 }, data: { template: "New inquiry from R. Chen:\n\nMy former employer is withholding my last two paychecks and threatening to enforce a non-compete I never signed. I have emails proving the missed payments. What are my options?" } },
      { id: "matter", type: "llm", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-haiku-4.5", system: "Classify this legal inquiry. Reply with exactly one lowercase word: contract, employment, or dispute.", prompt: "{{nodes.inquiry.output}}", temperature: 0, max_tokens: 5 } },
      { id: "route", type: "switch", position: { x: 820, y: 200 }, data: { mode: "contains", cases: "contract\nemployment\ndispute" } },
      { id: "contract", type: "llm", position: { x: 1090, y: 60 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a contracts paralegal. Draft intake notes: parties, agreement at issue, key dates, documents to request. Note: not legal advice.", prompt: "{{nodes.inquiry.output}}", max_tokens: 350 } },
      { id: "employment", type: "llm", position: { x: 1090, y: 210 }, data: { model: "anthropic/claude-sonnet-5", system: "You are an employment-law paralegal. Draft intake notes: employer, claims (wage withholding, non-compete), evidence available, urgency, documents to request. Note: not legal advice.", prompt: "{{nodes.inquiry.output}}", max_tokens: 350 } },
      { id: "dispute", type: "llm", position: { x: 1090, y: 360 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a litigation paralegal. Draft intake notes: parties, dispute summary, amount at stake, deadlines. Note: not legal advice.", prompt: "{{nodes.inquiry.output}}", max_tokens: 350 } },
      { id: "end", type: "end", position: { x: 1360, y: 210 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "inquiry" },
      { id: "e2", source: "inquiry", target: "matter" },
      { id: "e3", source: "matter", target: "route" },
      { id: "e4", source: "route", target: "contract", sourceHandle: "contract" },
      { id: "e5", source: "route", target: "employment", sourceHandle: "employment" },
      { id: "e6", source: "route", target: "dispute", sourceHandle: "dispute" },
      { id: "e7", source: "contract", target: "end" },
      { id: "e8", source: "employment", target: "end" },
      { id: "e9", source: "dispute", target: "end" },
    ],
  },
  {
    slug: "policy-checker",
    name: "Policy Checker",
    description: "Check a request against company policy — approve it or flag the violation.",
    glyph: "▣",
    accent: "#4fd1c5",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 200 }, data: {} },
      { id: "request", type: "prompt", position: { x: 300, y: 200 }, data: { template: "Expense claim from T. Okafor:\n$740 — team dinner for 4 people after the product launch, including two bottles of wine at $120 each." } },
      { id: "check", type: "llm", position: { x: 560, y: 200 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a policy compliance checker. Policy: meals capped at $75/person; alcohol not reimbursable; itemized receipt required over $200. Reply COMPLIANT or VIOLATION, then list each rule triggered.", prompt: "{{nodes.request.output}}", temperature: 0, max_tokens: 200 } },
      { id: "gate", type: "decision", position: { x: 820, y: 200 }, data: { mode: "contains", value: "VIOLATION" } },
      { id: "flag", type: "email", position: { x: 1080, y: 90 }, data: { to: "finance@example.com", subject: "Expense flagged: policy violation", body: "{{nodes.check.output}}\n\nOriginal claim:\n{{nodes.request.output}}" } },
      { id: "approve", type: "prompt", position: { x: 1080, y: 310 }, data: { template: "✅ Approved — within policy.\n\n{{nodes.check.output}}" } },
      { id: "end", type: "end", position: { x: 1350, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "request" },
      { id: "e2", source: "request", target: "check" },
      { id: "e3", source: "check", target: "gate" },
      { id: "e4", source: "gate", target: "flag", sourceHandle: "true" },
      { id: "e5", source: "gate", target: "approve", sourceHandle: "false" },
      { id: "e6", source: "flag", target: "end" },
      { id: "e7", source: "approve", target: "end" },
    ],
  },
  {
    slug: "kb-chat",
    name: "Knowledge Base Chat",
    description: "Answer a question strictly from your docs — admits when the answer isn't there.",
    glyph: "❝",
    accent: "#22d3ee",
    nodes: [
      { id: "hook", type: "webhook", position: { x: 60, y: 160 }, data: { path: "/hook/kb-chat" } },
      { id: "question", type: "prompt", position: { x: 320, y: 160 }, data: { template: "How do I rotate my API key, and do old keys keep working afterwards?" } },
      { id: "answer", type: "llm", position: { x: 580, y: 160 }, data: { model: "anthropic/claude-sonnet-5", system: "Answer ONLY from this knowledge base. If the answer isn't in it, say so and suggest contacting support.\n\nKB:\n- API keys: Settings → API Keys. 'Rotate' creates a new key; the old key keeps working for 24h, then dies.\n- Billing: invoices are emailed on the 1st; wallets top up in Settings → Billing.\n- SSO: available on Teams plan only, via SAML.", prompt: "{{nodes.question.output}}", temperature: 0.2, max_tokens: 300 } },
      { id: "end", type: "end", position: { x: 840, y: 160 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "hook", target: "question" },
      { id: "e2", source: "question", target: "answer" },
      { id: "e3", source: "answer", target: "end" },
    ],
  },
  {
    slug: "slack-digest",
    name: "Daily Slack Digest",
    description: "Draft a daily team brief and post it to Slack — schedule it to run every morning.",
    glyph: "＃",
    accent: "#22d3ee",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 160 }, data: {} },
      { id: "topic", type: "prompt", position: { x: 300, y: 160 }, data: { template: "Today's focus for an AI product team: shipping quality, watching costs, and talking to users." } },
      { id: "brief", type: "llm", position: { x: 560, y: 160 }, data: { model: "auto", system: "Write a crisp morning team digest: a one-line headline, then 3 bullets (priority, risk, quick win). Keep it under 90 words, plain text.", prompt: "{{nodes.topic.output}}", max_tokens: 300 } },
      { id: "post", type: "slack", position: { x: 820, y: 160 }, data: { webhook_url: "{{secrets.SLACK_WEBHOOK}}", message: "{{nodes.brief.output}}" } },
      { id: "end", type: "end", position: { x: 1080, y: 160 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "topic" },
      { id: "e2", source: "topic", target: "brief" },
      { id: "e3", source: "brief", target: "post" },
      { id: "e4", source: "post", target: "end" },
    ],
  },
  {
    slug: "network-troubleshoot",
    name: "Network Troubleshooting",
    description: "Diagnose an infra alert, propose fixes, and page on-call if it's critical.",
    glyph: "⇄",
    accent: "#4fd1c5",
    nodes: [
      { id: "hook", type: "webhook", position: { x: 60, y: 200 }, data: { path: "/hook/alerts" } },
      { id: "alert", type: "prompt", position: { x: 320, y: 200 }, data: { template: "ALERT [LibreNMS] core-sw-01: interface Gi1/0/48 flapping — 14 transitions in 10 min. Uplink to building B. CRC errors incrementing." } },
      { id: "diagnose", type: "llm", position: { x: 580, y: 200 }, data: { model: "anthropic/claude-sonnet-5", system: "You are a senior network engineer. Diagnose the alert: likely cause, 3 checks to run (with commands), and severity — end with exactly SEV1 or SEV2.", prompt: "{{nodes.alert.output}}", temperature: 0.2, max_tokens: 400 } },
      { id: "gate", type: "decision", position: { x: 840, y: 200 }, data: { mode: "contains", value: "SEV1" } },
      { id: "page", type: "email", position: { x: 1100, y: 90 }, data: { to: "netops-oncall@example.com", subject: "SEV1: core-sw-01 uplink flapping", body: "{{nodes.diagnose.output}}" } },
      { id: "log", type: "prompt", position: { x: 1100, y: 310 }, data: { template: "Logged SEV2 — queued for business hours.\n\n{{nodes.diagnose.output}}" } },
      { id: "end", type: "end", position: { x: 1370, y: 200 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "hook", target: "alert" },
      { id: "e2", source: "alert", target: "diagnose" },
      { id: "e3", source: "diagnose", target: "gate" },
      { id: "e4", source: "gate", target: "page", sourceHandle: "true" },
      { id: "e5", source: "gate", target: "log", sourceHandle: "false" },
      { id: "e6", source: "page", target: "end" },
      { id: "e7", source: "log", target: "end" },
    ],
  },
  {
    slug: "concept-to-image",
    name: "Concept → Image",
    description: "Turn a rough idea into a polished art-direction prompt, then render it with Nyquest image generation.",
    glyph: "✲",
    accent: "#2dd4bf",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 180 }, data: {} },
      { id: "idea", type: "prompt", position: { x: 300, y: 180 }, data: { template: "a friendly robot mascot for an AI workflow studio, teal and deep-space navy, minimal" } },
      { id: "direct", type: "llm", position: { x: 560, y: 180 }, data: { model: "anthropic/claude-haiku-4.5", system: "You are an art director. Rewrite the user's idea as a single vivid image-generation prompt: subject, style, palette, lighting, composition. Output only the prompt, one line, no preamble.", prompt: "{{nodes.idea.output}}", temperature: 0.7, max_tokens: 160 } },
      { id: "render", type: "nyquest_image", position: { x: 840, y: 180 }, data: { prompt: "{{nodes.direct.output}}", model: "imagen-4.0-fast-generate-001", aspect_ratio: "1:1" } },
      { id: "end", type: "end", position: { x: 1110, y: 180 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "idea" },
      { id: "e2", source: "idea", target: "direct" },
      { id: "e3", source: "direct", target: "render" },
      { id: "e4", source: "render", target: "end" },
    ],
  },
  {
    slug: "topic-to-narration",
    name: "Topic → Narration",
    description: "Turn a topic into a short spoken voiceover: LLM writes the script, then Nyquest speaks it.",
    glyph: "🔊",
    accent: "#2dd4bf",
    nodes: [
      { id: "start", type: "start", position: { x: 60, y: 180 }, data: {} },
      { id: "topic", type: "prompt", position: { x: 300, y: 180 }, data: { template: "the Nyquest compression engine, for a 15-second product teaser" } },
      { id: "script", type: "llm", position: { x: 560, y: 180 }, data: { model: "anthropic/claude-haiku-4.5", system: "You are a voiceover writer. Write two punchy spoken sentences (no stage directions, no quotes) for the given topic. Output only the words to be spoken.", prompt: "{{nodes.topic.output}}", temperature: 0.7, max_tokens: 120 } },
      { id: "voice", type: "nyquest_speech", position: { x: 840, y: 180 }, data: { text: "{{nodes.script.output}}", model: "gemini-2.5-flash-preview-tts", voice: "Kore" } },
      { id: "end", type: "end", position: { x: 1110, y: 180 }, data: {} },
    ],
    edges: [
      { id: "e1", source: "start", target: "topic" },
      { id: "e2", source: "topic", target: "script" },
      { id: "e3", source: "script", target: "voice" },
      { id: "e4", source: "voice", target: "end" },
    ],
  },
];
